version: '2'
services:

  data:
    image: busybox:latest
    volumes:
      - .:/var/project

  php:
    image: php:7-alpine
    command: php -v
    working_dir: /var/project
    volumes_from:
      - data

  crond:
    build:
      context: .
      dockerfile: docker/crond/Dockerfile
    privileged: true
    depends_on:
      - php
    volumes_from:
      - data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./crontab.conf:/var/spool/cron/crontabs/root
